"""add missing fields

Revision ID: d59112efe615
Revises: 17b409bd0f9d
Create Date: 2025-05-16 16:50:16.187216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59112efe615'
down_revision = '17b409bd0f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detailed_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_damage_taken', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_items_purchased', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detailed_analysis', schema=None) as batch_op:
        batch_op.drop_column('total_items_purchased')
        batch_op.drop_column('total_damage_taken')

    # ### end Alembic commands ###
